import swaggerJsdoc from 'swagger-jsdoc';
import swaggerUi from 'swagger-ui-express';
import pkg from '../../package.json' assert { type: 'json' };

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Simple Notes REST API Docs',
      version: pkg.version,
      description: 'Express API with autogenerated swagger doc',
    },
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          format: 'JWT',
        },
      },
    },
    security: [
      {
        bearerAuth: [],
      },
    ],
    servers: [
      {
        url: 'http://localhost:5000',
      },
    ],
  },
  apis: ['./src/routes/*.js'],
};

const specs = swaggerJsdoc(options);

export const swagger = (app) => {
  // Serve the Swagger UI
  app.use('/docs', swaggerUi.serve, swaggerUi.setup(specs));
  // Docs as JSON
  app.get('docs.json', (req, res) => {
    res.setHeader('Content-Type', 'application/json');
    res.send(swaggerUi.generateHTML(specs));
  });
};

export default swagger;
