name: CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          architecture: 'x64' # optional, x64 or x86. If not specified, x64 will be used by default
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
  
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run checks
        run: npm run lint

      - name: Run tests
        run: npm test
